//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.02 at 07:09:13 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://info/javateam/web/webservice/loginservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.javateam.web.webservice.loginservice;
